all: file

file:
	cd ./program1 && make all
	cd ./program2 && make all
	cd ./program3 && make all
	cd ./program4 && make all
	cd ./program5 && make all
	cd ./program6 && make all
	cd ./program7 && make all
	cd ./program8 && make all
	cd ./program9 && make all
	cd ./program10 && make all
	cp ./elf_files/* ../OS/elf_file/

clean:
	cd ./program1 && make clean
	cd ./program2 && make clean
	cd ./program3 && make clean
	cd ./program4 && make clean
	cd ./program5 && make clean
	cd ./program6 && make clean
	cd ./program7 && make clean
	cd ./program8 && make clean
	cd ./program9 && make clean
	cd ./program10 && make clean
